#server:
#  port: 8001
#
#mybatis:
#  type-aliases-package: com.wxr.springcloud.pojo
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
#
#spring:
#  application:
#    name: springcloud-provider-dept
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root
#
##eureka的配置，服务注册到哪里
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    instance-id: springcloud-provider-dept:8001 #修改eureka上的默认描述信息
#    prefer-ip-address: true #true，可以显示真实ip地址
#
##info配置
#info:
#  app.name: wxr-springcloud
#  company.name: 中国石化


spring:
  application:
    name: spring-cloud-config-dept