#server:
#  port: 80
#
#eureka:
#  client:
#    register-with-eureka: false #不向eureka注册自己
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#
##开启服务降级feign.hystrix
#feign:
#  hystrix:
#    enabled: true

spring:
  application:
    name: spring-cloud-consumer

feign:
  client:
    config:
      spring-cloud-config-dept:
        logger-level: basic #总共有四种日志级别 NONE，BASIC，HEADERS，FULL 一般默认的情况下是NONE，性能会很高，要么就是basic。